### ISSUE TITLE
Is it possible to run APP GUI in WSL？

### ISSUE THREAD

**Issue by wzy-99** [NVIDIAGameWorks/kaolin-wisp#104]
Hello, I tried to run Kaolin-wisp with GUI app in WSL2.

I use X11 server on my Windows11 to display the window.

But it seems not to work.

I run the example as `python3 main_demo.py --dataset-path /home/XXX/data/nerf_synthetic/lego`.

```bash
[i] Using GLFW (GL 2.1)
Traceback (most recent call last):
  File "/home/XXX/codes/kaolin-wisp/examples/latent_nerf/main_demo.py", line 10, in <module>
    setup_cuda_context()  # Must be called before any torch operations take place
  File "/home/XXX/codes/kaolin-wisp/wisp/cuda_guard.py", line 39, in setup_cuda_context
    import pycuda.gl.autoinit
  File "/home/XXX/codes/pycuda/pycuda/gl/autoinit.py", line 10, in <module>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
  File "/home/XXX/codes/pycuda/pycuda/tools.py", line 215, in make_default_context
    return ctx_maker(dev)
  File "/home/XXX/codes/pycuda/pycuda/gl/autoinit.py", line 10, in <lambda>
    context = make_default_context(lambda dev: cudagl.make_context(dev))
pycuda._driver.LogicError: cuGLCtxCreate failed: OS call failed or operation not supported on this OS
```

I just know the `pycuda` is used for display and it works at the GPU driver level.

For example, it will copy the RenderBuffer results to the screen buffer.

So, it is impossible to display the app window from WSL2, is right?

(I also tried to run Kaolin-wisp without GUI app in WSL2, and it works well.)

My device is GeForce 4090.

**Comment by orperel** [comment]
Hi @wzy-99 , I have an experimental PR for replacing `pycuda` with `cuda-python` directly.
Can you please give this a go and see if it works? 
https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/105

**Comment by orperel** [comment]
Thanks, that was helpful!
A little research suggests iNGP had a similar issue due to broken cuda-gl interop on WSL:
https://github.com/NVlabs/instant-ngp/issues/268

I've implemented a solution that doesn't use interop for WSL, can you please pull the latest from the PR branch and try again?
Specifically, in `WispApp` for WSL we should have `blitdevice2device=False` (hopefully the `is_wsl` check is correct, I have no means of testing that):
https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/105/files#diff-d13f3ce350b22c0df28a364d45ab84fd0c5f7312f866591151c79ad61dde81eeR118

**Comment by wzy-99** [comment]
![image](https://user-images.githubusercontent.com/44768324/212690968-6b0ed6ac-09b8-4912-91e1-f622cd97645b.png)

It works!
Thank you very much.
